import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

const inter = Inter({
   subsets: ['latin'],
   display: 'swap',
});

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='it'>
         <body className={`${inter.className}`}>{children}</body>
      </html>
   );
}
